<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>vwm</AssemblyName>
    <RootNamespace>Vwm.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Vwm.Core/Vwm.Core.csproj" />
  </ItemGroup>
</Project>
